//
//  Settings.m
//  PatternRecognizer
//
//  Copyright 2011 Syntellia Inc. All rights reserved.
//

#import "Settings.h"

bool FLEKSY_APP_SETTING_KEY_SNAP;
bool FLEKSY_APP_SETTING_INVISIBLE_KEYBOARD;
bool FLEKSY_APP_SETTING_TOUCH_HOME;
bool FLEKSY_APP_SETTING_SHOW_TRACES;
bool FLEKSY_APP_SETTING_SPEAK;
bool FLEKSY_APP_SETTING_KEYBOARD_CLICKS;
bool FLEKSY_APP_SETTING_USE_SYSTEM_AUTOCORRECTION;
bool FLEKSY_APP_SETTING_DICTATE_MODE;
bool FLEKSY_APP_SETTING_SHOW_SUGGESTIONS;
bool FLEKSY_APP_SETTING_LIVE_SUGGESTIONS;
NSString* FLEKSY_APP_SETTING_HOME_BUTTON_STRING;
NSString* FLEKSY_APP_SETTING_SPEED_DIAL_1;
NSString* FLEKSY_APP_SETTING_SMS_REPLY_TO;
NSString* FLEKSY_APP_SETTING_EMAIL_REPLY_TO;
float FLEKSY_APP_SETTING_SPEAKING_RATE;
int  FLEKSY_APP_SETTING_LOCK_ORIENTATION;
bool FLEKSY_APP_SETTING_SPELL_WORDS;
bool FLEKSY_APP_SETTING_RAISE_TO_SPEAK;
NSString* FLEKSY_APP_SETTING_EMAIL_SIGNATURE;
bool FLEKSY_APP_SETTING_EMAIL_INCLUDE_FIRST_LINE;
bool FLEKSY_APP_SETTING_SPACE_BUTTON;
NSString* FLEKSY_APP_SETTING_LANGUAGE_PACK;
int FLEKSY_APP_SETTING_THEME;
// Only saved locally, not across devices
bool FLEKSY_APP_CACHE_WSJ_QUESTIONAIRE;
bool FLEKSY_APP_SETTING_COPY_ON_EXIT;



