#!/bin/sh

#  BuildInfo.sh
#  Fleksy
#
#  Created by John Engelhart on 3/27/13.
#  Copyright (c) 2012 Syntellia Inc. All rights reserved.

printf "// THIS FILE IS AUTOMATICALLY GENERATED!\n// ANY MODIFICATIONS WILL BE LOST!\n// Generated on `date`\n\n" >"${SRCROOT}/${FL_BUILD_INFO_FILE}"

/usr/bin/perl -i -e 'chomp($SHORTHASH=`cd "$ENV{SRCROOT}"; git rev-parse --short HEAD`) or die "Could not get git short hash."; $SHORTHASH =~ /[0-9a-fA-F]{4,12}/ or die "The extracted git short hash <$SHORTHASH> does not appear to be valid."; print "FL_GIT_SHORTHASH = $SHORTHASH;\n\n";' >>"${SRCROOT}/${FL_BUILD_INFO_FILE}"


printf "// From file \"${FL_BUILDUTIL_DIR}/TestFlightVersion.xcconfig\"\n" >>"${SRCROOT}/${FL_BUILD_INFO_FILE}"
cat "${SRCROOT}/${FL_BUILDUTIL_DIR}/TestFlightVersion.xcconfig" >>"${SRCROOT}/${FL_BUILD_INFO_FILE}"

#if [ "${CONFIGURATION}" == "TestFlight" ]; then
#/usr/bin/perl -pi -e 's/(^\s*FL_TESTFLIGHT_BUILD_NUMBER\s*=\s*)(\d+)/$1.($2+1)/eg' "${SRCROOT}/${FL_BUILD_INFO_FILE}"
#fi;
